Prefer options.sendBeacon to options.blob
PostHog/posthog-js pull request #300
Opened 2021-09-30 13:05 UTC by pauldambra

## Changes

if we gzip encode data we set options.Blob to true, if we then send that data using sendBeacon, we were calling encodePostData with both options.Blob and options.sendBeacon set to true

encodePostData preferred options.Blob to options.sendBeacon and executes a different code path for each.

This switches that preference 

## Checklist
- [x] Tests for new code (if applicable)

2021-09-30 13:19 UTC, pauldambra commented
This feels more correct in isolation. I'm trying to puzzle through what the consequences of each code path are...

2021-09-30 13:27 UTC, pauldambra commented
If the `options.blob` code is processed when the input data is an array of bytes the output is `["Blob", [undefined], {"type": "text/plain"}]`

2021-09-30 17:28 UTC, pauldambra commented
Have shifted to "draft" status for clarity. Am convinced this is (the|a) source of the issue but not convinced I fully understand the consequence of the change yet

2021-10-05 10:41 UTC, mariusandra requested changes
I think it looks good... just one annoying compatibility issue

2021-10-05 10:45 UTC, pauldambra commented on src/send-request.js
> +    const isTypedArray = (d) => ArrayBuffer.isView(d) && Object.prototype.toString.call(d) !== '[object DataView]'
:) will take a look

2021-10-05 11:21 UTC, pauldambra commented on src/send-request.js
> +    const isTypedArray = (d) => ArrayBuffer.isView(d) && Object.prototype.toString.call(d) !== '[object DataView]'
Manually confirmed on browserstack in Windows 10 IE 11
![Screenshot 2021-10-05 at 12 20 44](https://user-images.githubusercontent.com/984817/136013406-e4a95396-ed5e-437b-9544-5af5928dd6d5.png)

2021-10-06 10:12 UTC, yakkomajuri approved these changes
We talked this over during a pairing session and made a few minor changes.

LGTM!

2021-10-06 10:12 UTC, merged