PROPOSAL: Send lib version in http header
PostHog/posthog-js pull request #351
Opened 2022-01-07 20:52 UTC by pauldambra

## Changes

We add the library version to event properties. This is really useful when debugging problems. 

When decompression of the request body fails we get an error report in Sentry. But we can't add the library version to the Sentry report because it is inside the compressed content. 

This change adds the lib version to an HTTP header so that it would always be available in Sentry. We could (optionally) follow up by having the backend add that library version as a tag to Sentry so we get richer behaviour in the Sentry UI

## Checklist
- [x] Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))
- [x] Accounted for the impact of any changes across different browsers
- [ x TypeScript definitions (module.d.ts) updated and in sync with library exports (if applicable)

2022-01-20 10:05 UTC, mariusandra commented
There's already a standard way to describe who's making a request: the `user-agent` header. This is also what [one of our competitors](https://github.com/segmentio/analytics-node/blob/master/index.js#L276-L279) does.

I'd suggest following a similar pattern, since we don't have just one "Lib" either.

2022-02-15 10:20 UTC, mariusandra commented
I think I need to do a 🤦 here. When reviewing this now, I started to wonder if setting a user agent in a browser is something that's done... and if some adblockers might consider that a strong signal that the user is up to something malicious or not. Apparently doing this [was disallowed](https://stackoverflow.com/a/42815264) not so long ago... so it could be penalised, tracked or just flakey yet again.

The [link I copied in my previous comment](https://github.com/segmentio/analytics-node/blob/master/index.js#L276-L279) shows actually the exact opposite of what I said in the comment itself. It's for the `-node` library and writes `// Don't set the user agent if we're on a browser.`

🤦 

How would you like to proceed? 😅 😢

2022-02-15 10:50 UTC, pauldambra commented
Hmmm 🤔 

The nice thing about user-agent is that it's sort-of semantically correct. How about `posthog-user-agent`?

2022-03-01 09:13 UTC, mariusandra commented
I still think:

1) This `posthog-user-agent` header makes a lot of sense from a practical perspective, and does indeed give us more debug help.
2) I'm scared this will allow adblockers to surgically disable all posthog-js requests, even if it's a first-party request to a self-hosted instance.

So... I'm still on the fence. Better be cautious? Could perhaps a ?v=1.2.3 style GET param be less obviously taggable while providing the same debug info?

Tagging a few people for a second opinion: @timgl @macobo @Twixes @guidoiaquinti

2022-03-01 09:19 UTC, macobo commented
There are a lot of things that make me paranoid about this change:

1. Old browser support
2. Whether this affects CORS
3. Whether this changes the way compression works/xhr
4. Whether it increases the chance of getting blocked

I'd be cautiously for either a GET parameter or testing the heck out of this in a real-world setting.

2022-03-01 10:03 UTC, guidoiaquinti commented
This is a bit outside my area of expertise. From a technical perspective, the user-agent is the solution I would use. From a business perspective I'm not sure it is the right solution.

2022-03-01 13:13 UTC, timgl commented
I think Karl's points are valid. The simplest way of verifying whether this works is to make this a config option in posthog-js and set that config on our own website/app to start with. Then in a week or so we can see if we dropped events from any browser and if we're seeing any other errors.

2022-03-15 08:20 UTC, mariusandra requested changes
some suggestions

2022-03-15 08:20 UTC, mariusandra commented on src/send-request.js
> +    console.log(parameterOptions, 'poo')
log `poo`

2022-03-15 08:20 UTC, mariusandra commented on cypress/integration/capture.spec.js
> +const urlWithLibraryAndVersion = new RegExp(`&l=web&v=${version}`)
I think `l=web&v=` is a pretty uniquely matchable pattern for aggressive traffic blockers, so perhaps we should infer `web` by default if only `v` is present? Other integrations than posthog-js can send it if they want, but there are benefits to not exposing it here.

2022-03-15 08:20 UTC, mariusandra commented on cypress/integration/capture.spec.js
> +                _library_and_version_in_query_params: true,
I don't think this needs to be an option you configure. Just turn it on.

2022-03-22 10:50 UTC, mariusandra approved these changes

2022-03-22 10:50 UTC, merged