feat: Exception Autocapture
PostHog/posthog-js pull request #649
Opened 2023-05-26 12:01 UTC by pauldambra

## Changes

The tired brain version of exception autocapture

2023-05-28 14:06 UTC, pauldambra commented on src/types.ts
> +    exception_autocapture: boolean
```suggestion
    // this is currently in development and may have breaking changes without a major version bump
    exception_autocapture: boolean
```

2023-05-30 08:03 UTC, benjackwhite reviewed
Some first pass comments. Will take a proper look at the exception code in a bit

2023-05-30 08:03 UTC, benjackwhite commented on src/extensions/exceptions/exception-autocapture.ts
> +            }
We have `get_session_replay_url()` now which should be used here. 

One thought though - why do we want this 🤔 is it not redundant given that we can rebuild it on the other end?

2023-05-30 08:03 UTC, benjackwhite commented on src/posthog-core.ts
> +    exception_autocapture: false,
Feels a little weird that we have `exception_autocapture` locally and `autocaptureExceptions` remotely... Not sure if that means it should be different but it feels confusing...

2023-05-30 08:04 UTC, benjackwhite reviewed
Some first pass comments. Will take a proper look at the exception code in a bit

2023-05-31 09:46 UTC, benjackwhite requested changes
Small changes but overall this looks great. Didn't review the "inspired" code too deeply but it all looks very clever ;)

2023-05-31 11:10 UTC, merged