feat: different rate limiting handling
PostHog/posthog-js pull request #765
Opened 2023-07-27 14:49 UTC by pauldambra

the last attempt didn't play nicely with older clients...

Now

* capture still returns 200 when rate limiting but includes a list of rate limited products in the body
* the rate limiter uses the batch key or defaults to events (currently recordings sets a batch key and events doesn't)
* we rate limit for 1 minute
* we don't check for rate limiting on every response since there's no need to parse json for every request just in case there's been limiting

2023-07-28 10:42 UTC, pauldambra commented on src/extensions/sessionrecording.ts
> +            new MutationRateLimiter(this.rrwebRecord, {
this is checked above so doesn't need the not null assertion

2023-07-28 10:44 UTC, pauldambra commented on src/send-request.ts
> +                // don't retry errors between 400 and 500 inclusive
sneaky fly-by - I think this is neater but 🤷

2023-07-31 12:36 UTC, benjackwhite requested changes
Looks good! Small comments but the core looks great

2023-07-31 12:36 UTC, benjackwhite commented on src/rate-limiter.ts
> +            // we don't need to check this on every request
I find this a little confusing. Why do we only need to check now and then? 
Feels like a step that could be confusing to us in the future when we still see a lot of requests coming in.

Is the subsequent code super slow or something? Seems like fairly straightforward code so I wouldn't say the perf benefits outweigh the extra complexity personally

2023-07-31 12:36 UTC, benjackwhite commented on src/rate-limiter.ts
> +                }
Don't we have a logger util for exactly this?

2023-08-02 06:50 UTC, benjackwhite approved these changes
👍

2023-08-18 09:58 UTC, benjackwhite approved these changes

2023-09-13 19:57 UTC, merged