fix(surveys): Validate HTML for all questions and descriptions
PostHog/posthog-js pull request #824
Opened 2023-10-05 16:13 UTC by neilkakkar

## Changes

Part 1 of 2 of custom HTML support in surveys. This ensures parsed HTML is safe and valid to use
...

## Checklist
- [ ] Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))
- [ ] Accounted for the impact of any changes across different browsers

2023-10-06 13:02 UTC, neilkakkar commented
the cost of purifying & bundling together is a bigger package 😬

2023-10-06 13:28 UTC, neilkakkar commented on rollup.config.js
> +        plugins: [resolve(), ...plugins],
Actually, the `resolve()` configuration options for other things doesn't _appear_ to make a difference, do you remember what it was for?

2023-10-06 15:10 UTC, liyiy approved these changes

2023-10-06 15:10 UTC, liyiy commented on src/extensions/surveys.ts
> +// import { sanitize } from 'dompurify'
commented out code

2023-10-06 15:14 UTC, neilkakkar commented on src/extensions/surveys.ts
> +// import { sanitize } from 'dompurify'
nice thanks

2023-10-06 15:25 UTC, jurajmajerik approved these changes

2023-10-09 11:06 UTC, benjackwhite requested changes
Personally I am not a fan of this. 22kb of extra JS just to make sure the html is valid and pure which _could_ instead be done at write time instead? 

Is there a reason why we aren't doing this in app.posthog.com instead?

2023-10-09 11:06 UTC, benjackwhite commented on rollup.config.js
> +        plugins: [resolve(), ...plugins],
No idea 🙈

2023-10-09 13:30 UTC, closed without merging

2023-10-09 13:30 UTC, neilkakkar commented
Discussed offline, conclusion is @benjackwhite convinced me that my reluctance to do this validation on the backend is not worth the trade-offs. Bigger package size is annoying to users, plus the security concern of people being able to bypass our API isn't big enough to warrant sanitisation in the frontend. (if that can happen, we have much more serious issues to deal with)

2023-10-09 14:00 UTC, neilkakkar commented
And at the same time, the feature to allow scripts / custom HTML rendering via survey API mode is also something we're not going to support. Since it's API mode, they can just add this to the code themselves, rather than parsing these scripts via the survey itself.